### ISSUE TITLE
 Encountered an error

### ISSUE THREAD

**Issue by JimmyJune** [brownvc/diffdiffdepth#1]
run cmd:
python run_mvs.py --input_dir=/home/jimmy/oss/Project/video_sample/keyframes/VID_20210901_112934 --src_img=00001.jpeg --output_dir=./results

error:
Traceback (most recent call last):
  File "run_mvs.py", line 179, in <module>
    optimize(args.input_dir, args.src_img, args.output_dir)
  File "run_mvs.py", line 102, in optimize
    optim_param(optimizer_s)
  File "run_mvs.py", line 75, in optim_param
    torch.tensor(config.tile_max_pts), config.factor, config.loss_VGG, config.loss_grad, config.loss_smoothness)
  File "/home/jimmy/oss/Project/diffdiffdepth/loss.py", line 97, in loss_mvs
    gy) # gradient weights, y
  File "/home/jimmy/oss/Project/diffdiffdepth/LAHBPCG.py", line 486, in set_constraints
    self.AD = sx + sx_r + w + sy + sy_r
RuntimeError: The size of tensor a (3840) must match the size of tensor b (3780) at non-singleton dimension 2

**Comment by noobtoob4lyfe** [comment]
I'm getting the same error.  Any luck getting past this?

**Comment by sjtu-medialab** [comment]
I'm getting the same error. Any luck getting past this?
